# Generated by Django 5.2 on 2025-04-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amoumt',
            new_name='amount',
        ),
    ]
